### ISSUE TITLE
Error  with keyError

### ISSUE THREAD

**Issue by huangnengCSU** [vahidAK/SNVoter#1]
Hi，
I am trying to run SNVoter to improve the SV and SNP prediction, but there is an error. I think it is due to some unexpected bases in the reference or raw reads.

Here is my command:
```
CUDA_VISIBLE_DEVICES=7 snvoter prediction -i snp_and_indel.vcf.gz -b GM24149_50X.sort.bam -r GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna -t 60 -o SNVoter_snp_and_indel
```
The input file `snp_and_indel.vcf.gz` is generated by Clair. And the error information is as follows:
```
Using TensorFlow backend.
2021-03-10 11:51:53.077716: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
2021-03-10 11:51:53.180895: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2100000000 Hz
2021-03-10 11:51:53.191931: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55cfc54ece30 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-03-10 11:51:53.191998: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-03-10 11:51:53.203272: I tensorflow/core/common_runtime/process_util.cc:147] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
Processing:  16%|██████████████████████████████████▏                                                                                                                                                                                         [ Estimated time left: 11:59:12 ]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/snvoter/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/user/miniconda3/envs/snvoter/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/user/miniconda3/envs/snvoter/lib/python3.7/site-packages/snvoter/__main__.py", line 230, in window_mutation
    kmer_dumy.extend(encoder[base])
KeyError: 'W'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/miniconda3/envs/snvoter/bin/snvoter", line 8, in <module>
    sys.exit(main())
  File "/home/user/miniconda3/envs/snvoter/lib/python3.7/site-packages/snvoter/__main__.py", line 686, in main
    args.func(args)
  File "/home/user/miniconda3/envs/snvoter/lib/python3.7/site-packages/snvoter/__main__.py", line 399, in main_prediction
    repeat(args.depth))))
  File "/home/user/miniconda3/envs/snvoter/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/user/miniconda3/envs/snvoter/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
KeyError: 'W'

```
Can you fix this problem? 
Thanks,
Huang Neng

**Comment by vahidAK** [comment]
Hi @huangnengCSU ,
Yes, it was working only for A,T,C,G bases and I was working to fix it. I have just updated the code as the new version v1.1 which should be working for all IUPAC bases.
Could you please clone the repo again and let me know if it is working?

Thanks,
Vahid
